/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package octographs;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.Vector;
import javax.swing.AbstractListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListCellRenderer;
import javax.swing.ListModel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author audoban
 */
class RowHeaderRenderer extends JLabel implements ListCellRenderer {

    RowHeaderRenderer(JTable table) {
        JTableHeader header = table.getTableHeader();
        setOpaque(true);
        setBorder(UIManager.getBorder("TableHeader.cellBorder"));
        setHorizontalAlignment(CENTER);
        setForeground(header.getForeground());
        setBackground(header.getBackground());
        setFont(header.getFont());
    }

    public Component getListCellRendererComponent(JList list, Object value,
            int index, boolean isSelected, boolean cellHasFocus) {
        setText((value == null) ? "" : value.toString());
        return this;
    }
}

public class FrameMAdyacencia extends javax.swing.JFrame {

    /**
     * Creates new form FrameMAdyacencia
     */
   

    public FrameMAdyacencia(Proceso proceso) {
        this.proceso = proceso;
        initComponents();
        initTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboxMA = new javax.swing.JComboBox();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 8), new java.awt.Dimension(5, 8), new java.awt.Dimension(5, 8));
        panel = new javax.swing.JPanel();
        mA = new javax.swing.JScrollPane();
        tMA = new javax.swing.JTable();
        mA2 = new javax.swing.JScrollPane();
        tMA2 = new javax.swing.JTable();
        mA3 = new javax.swing.JScrollPane();
        tMA3 = new javax.swing.JTable();
        mA4 = new javax.swing.JScrollPane();
        tMA4 = new javax.swing.JTable();
        mA5 = new javax.swing.JScrollPane();
        tMA5 = new javax.swing.JTable();

        setTitle("Matriz de adyacencia");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        cboxMA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Matriz de adyacencia", "Matriz de caminos de longitud 2", "Matriz de caminos de longitud 3", "Matriz de caminos de longitud 4", "Matriz de caminos de longitud 5" }));
        cboxMA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxMAItemStateChanged(evt);
            }
        });
        getContentPane().add(cboxMA);
        getContentPane().add(filler1);

        panel.setLayout(new java.awt.CardLayout());

        tMA.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tMA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        tMA.setRowHeight(20);
        tMA.getTableHeader().setReorderingAllowed(false);
        mA.setViewportView(tMA);

        panel.add(mA, "Matriz de adyacencia");

        tMA2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tMA2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0"}
            },
            new String [] {
                "Item"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tMA2.setRowHeight(20);
        tMA2.getTableHeader().setReorderingAllowed(false);
        mA2.setViewportView(tMA2);

        panel.add(mA2, "Matriz de caminos de longitud 2");

        tMA3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tMA3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0"}
            },
            new String [] {
                "Item"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tMA3.setRowHeight(20);
        tMA3.getTableHeader().setReorderingAllowed(false);
        mA3.setViewportView(tMA3);

        panel.add(mA3, "Matriz de caminos de longitud 3");

        tMA4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tMA4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0"}
            },
            new String [] {
                "Item"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tMA4.setRowHeight(20);
        tMA4.getTableHeader().setReorderingAllowed(false);
        mA4.setViewportView(tMA4);

        panel.add(mA4, "Matriz de caminos de longitud 4");

        tMA5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tMA5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        tMA5.setRowHeight(20);
        tMA5.getTableHeader().setReorderingAllowed(false);
        mA5.setViewportView(tMA5);

        panel.add(mA5, "Matriz de caminos de longitud 5");

        getContentPane().add(panel);

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxMAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxMAItemStateChanged
        CardLayout cl = (CardLayout) (panel.getLayout());
        cl.show(panel, (String)evt.getItem());
        this.setTitle((String)evt.getItem());
    }//GEN-LAST:event_cboxMAItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMAdyacencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMAdyacencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMAdyacencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMAdyacencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMAdyacencia(null).setVisible(true);
            }
        });
    }

    private Proceso proceso;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboxMA;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane mA;
    private javax.swing.JScrollPane mA2;
    private javax.swing.JScrollPane mA3;
    private javax.swing.JScrollPane mA4;
    private javax.swing.JScrollPane mA5;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tMA;
    private javax.swing.JTable tMA2;
    private javax.swing.JTable tMA3;
    private javax.swing.JTable tMA4;
    private javax.swing.JTable tMA5;
    // End of variables declaration//GEN-END:variables

    private void initTables() {
        if(proceso == null) return;
        createTable(tMA, mA, proceso.getMatrizAdyacencia());
        createTable(tMA2, mA2, proceso.adyPotencia(2));
        createTable(tMA3, mA3, proceso.adyPotencia(3));
        createTable(tMA4, mA4, proceso.adyPotencia(4));
        createTable(tMA5, mA5, proceso.adyPotencia(5));
    }

    private void createTable(JTable table, JScrollPane scroll, int[][] data) {
        DefaultTableModel model = new DefaultTableModel(proceso.ORDEN, proceso.ORDEN);       
        Object[] nodos = new Object[proceso.ORDEN];
        System.arraycopy(proceso.getNodos(), 0, nodos, 0, nodos.length);
        model.setColumnIdentifiers(nodos);
        for (int i = 0; i < proceso.ORDEN; i++) {
            for (int j = 0; j < proceso.ORDEN; j++) {
                model.setValueAt(data[i][j], i, j);
            }
        }
        table.setModel(model);

        JList rowHeader = new JList(proceso.getNodos());
        rowHeader.setCellRenderer(new RowHeaderRenderer(table));
        rowHeader.setFixedCellWidth(50);
        rowHeader.setFixedCellHeight(20);
        scroll.setRowHeaderView(rowHeader);
    }
}
