/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package octographs;

/**
 *
 * @author Sebastian Anderson
 */
public class UI extends javax.swing.JPanel
{

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public UI()
    {
        initComponents();
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lienzo = new octographs.Lienzo();
        toolBar = new javax.swing.JToolBar();
        btnMAdyacencia = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0));
        btnRecorridos = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0));
        btnLimpiar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());
        add(lienzo, java.awt.BorderLayout.CENTER);

        toolBar.setFloatable(false);
        toolBar.setRollover(true);
        toolBar.setFocusCycleRoot(true);
        toolBar.setName(""); // NOI18N

        btnMAdyacencia.setText("Matríces Adyacencia");
        btnMAdyacencia.setActionCommand("btnMatriz");
        btnMAdyacencia.setFocusable(false);
        btnMAdyacencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMAdyacencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMAdyacencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMAdyacenciaActionPerformed(evt);
            }
        });
        toolBar.add(btnMAdyacencia);
        toolBar.add(filler1);
        toolBar.add(filler2);

        btnRecorridos.setText("Recorridos");
        btnRecorridos.setFocusable(false);
        btnRecorridos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRecorridos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRecorridos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecorridosActionPerformed(evt);
            }
        });
        toolBar.add(btnRecorridos);
        toolBar.add(filler3);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setFocusable(false);
        btnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        toolBar.add(btnLimpiar);

        add(toolBar, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    private void btnMAdyacenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMAdyacenciaActionPerformed
        Proceso pr = new Proceso(lienzo.relaciones, lienzo.elementos);
        if (pr.ORDEN == 0)
            return;
        FrameMAdyacencia fr = new FrameMAdyacencia(pr);
        fr.setVisible(true);
    }//GEN-LAST:event_btnMAdyacenciaActionPerformed

    
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        lienzo.limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRecorridosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecorridosActionPerformed
        Proceso pr = new Proceso(lienzo.relaciones, lienzo.elementos);
        if (pr.ORDEN == 0) 
            return;
        FrameRecorrido frame = new FrameRecorrido(pr);
        frame.setVisible(true);
    }//GEN-LAST:event_btnRecorridosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMAdyacencia;
    private javax.swing.JButton btnRecorridos;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private octographs.Lienzo lienzo;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables

}
