/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package octographs;

import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sebastian Anderson
 */
public class UI extends javax.swing.JPanel {

    DefaultTableModel modelo;
    public UI() {
        initComponents();
        String cabezera [] = {"propiedades","si","no-","anti-"};
        String datos [][] = {};        
        modelo = new DefaultTableModel(datos, cabezera);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lienzo1 = new octographs.Lienzo();
        PnlBotones = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnLimpiar = new javax.swing.JButton();
        btnMatriz = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jMA = new javax.swing.JTextArea();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel1.setText("jLabel1");

        setLayout(new java.awt.GridLayout(3, 1));
        add(lienzo1);

        PnlBotones.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        PnlBotones.setLayout(new javax.swing.BoxLayout(PnlBotones, javax.swing.BoxLayout.LINE_AXIS));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnLimpiar);
        btnLimpiar.setBounds(505, 100, 90, 23);

        btnMatriz.setText("Matríces Adyacencia");
        btnMatriz.setActionCommand("btnMatriz");
        btnMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatrizActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnMatriz);
        btnMatriz.setBounds(20, 60, 140, 23);

        jLabel2.setText("MA");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(80, 130, 20, 14);

        PnlBotones.add(jLayeredPane1);

        add(PnlBotones);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jMA.setColumns(20);
        jMA.setRows(5);
        jScrollPane6.setViewportView(jMA);

        jLayeredPane2.add(jScrollPane6);
        jScrollPane6.setBounds(0, 0, 190, 150);

        jPanel1.add(jLayeredPane2);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

   
     
     
    private void btnMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatrizActionPerformed
     // Crea las matrices de adyacencia
        
        //Variables
        Proceso pro = new Proceso(lienzo1.relaciones,lienzo1.elementos);
        int m2 [][] = new int[pro.matrizAdyacencia.length][pro.matrizAdyacencia.length];
        int m3 [][] = new int[pro.matrizAdyacencia.length][pro.matrizAdyacencia.length];
        int m4 [][] = new int[pro.matrizAdyacencia.length][pro.matrizAdyacencia.length];
        int m5 [][] = new int[pro.matrizAdyacencia.length][pro.matrizAdyacencia.length];
        // Procedimiento Matriz Adyacente
        jMA.setText("");
        jMA.setRows(lienzo1.elementos.size() + 1);
        jMA.setColumns(lienzo1.elementos.size() + 1);

        for(int i = 0; i< pro.matrizAdyacencia.length;i++){
            String x = "";
            for(int j = 0; j < pro.matrizAdyacencia.length;j++){                                
             System.out.print(pro.matrizAdyacencia[i][j]+ " ");
             x += " " + pro.matrizAdyacencia[i][j];
            }
            jMA.append(x + "\n");
        }
        // Matriz adyacente^2
        jMA.append("\n");
        jMA.append("MA^2");
        jMA.append("\n");
        
        for(int x=0;x<pro.matrizAdyacencia.length;x++){
            String r="";
            for(int y=0; y<pro.matrizAdyacencia.length;y++){
                for(int m=0; m<pro.matrizAdyacencia.length;m++){
                    m2[x][y] += pro.matrizAdyacencia[x][m]*pro.matrizAdyacencia[m][y];                    
                }
                r += " "+ m2[x][y];               
            }
            jMA.append(r+"\n");
        }
        
        // Matriz adyacente^3
        jMA.append("\n");
        jMA.append("MA^3");
        jMA.append("\n");
        
        for(int x=0;x<pro.matrizAdyacencia.length;x++){
            String r="";
            for(int y=0; y<pro.matrizAdyacencia.length;y++){
                for(int m=0; m<pro.matrizAdyacencia.length;m++){
                    m3[x][y] += m2[x][m]*pro.matrizAdyacencia[m][y];                    
                }
                r += " "+ m3[x][y];               
            }
            jMA.append(r+"\n");
        }
        
        // Matriz adyacente^4
        jMA.append("\n");
        jMA.append("MA^4");
        jMA.append("\n");
        
        for(int x=0;x<pro.matrizAdyacencia.length;x++){
            String r="";
            for(int y=0; y<pro.matrizAdyacencia.length;y++){
                for(int m=0; m<pro.matrizAdyacencia.length;m++){
                    m4[x][y] += m3[x][m]*pro.matrizAdyacencia[m][y];                    
                }
                r += " "+ m4[x][y];               
            }
            jMA.append(r+"\n");
        }
        
        // Matriz adyacente^5
        jMA.append("\n");
        jMA.append("MA^5");
        jMA.append("\n");
        
        for(int x=0;x<pro.matrizAdyacencia.length;x++){
            String r="";
            for(int y=0; y<pro.matrizAdyacencia.length;y++){
                for(int m=0; m<pro.matrizAdyacencia.length;m++){
                    m5[x][y] += m4[x][m]*pro.matrizAdyacencia[m][y];                    
                }
                r += " "+ m5[x][y];               
            }
            jMA.append(r+"\n");
        }
        
        
        System.out.println("Botón matríz");
    }//GEN-LAST:event_btnMatrizActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        
        jMA.setText("");

        
        
        for(int i = 0; i < modelo.getRowCount();i++){
            modelo.removeRow(0);
            modelo.removeRow(0);
            }
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlBotones;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMatriz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JTextArea jMA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private octographs.Lienzo lienzo1;
    // End of variables declaration//GEN-END:variables

    
}

