/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package octographs;

import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sebastian Anderson
 */
public class UI extends javax.swing.JPanel {

    DefaultTableModel modelo;
    public UI() {
        initComponents();
        String cabezera [] = {"propiedades","si","no-","anti-"};
        String datos [][] = {};
        modelo = new DefaultTableModel(datos, cabezera);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lienzo1 = new octographs.Lienzo();
        PnlBotones = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnLimpiar = new javax.swing.JButton();
        btnMatriz = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jMA = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        jMa2 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        jMa3 = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        jMa5 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        jMa4 = new javax.swing.JTextArea();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel1.setText("jLabel1");

        setLayout(new java.awt.GridLayout(3, 1));
        add(lienzo1);

        PnlBotones.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        PnlBotones.setLayout(new javax.swing.BoxLayout(PnlBotones, javax.swing.BoxLayout.LINE_AXIS));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnLimpiar);
        btnLimpiar.setBounds(400, 10, 65, 23);

        btnMatriz.setText("Matríces Adyacencia");
        btnMatriz.setActionCommand("btnMatriz");
        btnMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatrizActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnMatriz);
        btnMatriz.setBounds(30, 10, 140, 23);

        jLabel2.setText("MA");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(40, 110, 20, 14);

        jLabel3.setText("MA^2");
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(160, 110, 29, 14);

        jLabel4.setText("MA^3");
        jLayeredPane1.add(jLabel4);
        jLabel4.setBounds(280, 110, 29, 14);

        jLabel5.setText("MA^4");
        jLayeredPane1.add(jLabel5);
        jLabel5.setBounds(410, 110, 29, 14);

        jLabel6.setText("MA^5");
        jLayeredPane1.add(jLabel6);
        jLabel6.setBounds(540, 110, 30, 14);

        PnlBotones.add(jLayeredPane1);

        add(PnlBotones);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jMA.setColumns(20);
        jMA.setRows(5);
        jScrollPane6.setViewportView(jMA);

        jLayeredPane2.add(jScrollPane6);
        jScrollPane6.setBounds(0, 10, 120, 100);

        jMa2.setColumns(20);
        jMa2.setRows(5);
        jMa2.setToolTipText("");
        jScrollPane11.setViewportView(jMa2);
        jMa2.getAccessibleContext().setAccessibleName("jMa2");
        jMa2.getAccessibleContext().setAccessibleDescription("jMa2");
        jMa2.getAccessibleContext().setAccessibleParent(null);

        jLayeredPane2.add(jScrollPane11);
        jScrollPane11.setBounds(120, 10, 120, 100);

        jMa3.setColumns(20);
        jMa3.setRows(5);
        jScrollPane12.setViewportView(jMa3);

        jLayeredPane2.add(jScrollPane12);
        jScrollPane12.setBounds(240, 10, 130, 100);

        jMa5.setColumns(20);
        jMa5.setRows(5);
        jScrollPane13.setViewportView(jMa5);

        jLayeredPane2.add(jScrollPane13);
        jScrollPane13.setBounds(500, 10, 120, 100);

        jMa4.setColumns(20);
        jMa4.setRows(5);
        jScrollPane14.setViewportView(jMa4);

        jLayeredPane2.add(jScrollPane14);
        jScrollPane14.setBounds(370, 10, 130, 100);

        jPanel1.add(jLayeredPane2);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

   
     
     
    private void btnMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatrizActionPerformed
     //UI UI = new UI();
        Proceso pro = new Proceso(lienzo1.relaciones,lienzo1.elementos);//pcc
        jMA.setText("");
        jMA.setRows(lienzo1.elementos.size() + 1);
        jMA.setColumns(lienzo1.elementos.size() + 1);

        for(int i = 0; i< pro.matrizAdyasencia.length;i++){
            String x = "";
            for(int j = 0; j < pro.matrizAdyasencia.length;j++){                                
             System.out.print(pro.matrizAdyasencia[i][j]+ " ");
             x += " " + pro.matrizAdyasencia[i][j];
            }
            jMA.append(x + "\n");
        }
        System.out.println("Botón matríz");
    }//GEN-LAST:event_btnMatrizActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        
        jMA.setText("");

        
        
        for(int i = 0; i < modelo.getRowCount();i++){
            modelo.removeRow(0);
            modelo.removeRow(0);
            }
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlBotones;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMatriz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JTextArea jMA;
    private javax.swing.JTextArea jMa2;
    private javax.swing.JTextArea jMa3;
    private javax.swing.JTextArea jMa4;
    private javax.swing.JTextArea jMa5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private octographs.Lienzo lienzo1;
    // End of variables declaration//GEN-END:variables

    
}

